
version: 2.1
parameters:
  cci-hostname:
    type: string
    default: "cci-server-test.eks-dev.sphereci.com"
executors:
  default:
    docker:
      - image: cimg/base:stable
jobs:
  get-job-v1-cloud:
    executor: default
    steps:
      - run: 
          name: getJob v1
          command: |
             curl https://circleci.com/api/v1.1/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/4 -H "Circle-Token: $CIRCLE_TOKEN"

  
  get-job-v2-cloud:
    executor: default
    steps:
      - run: 
          name: getJob v2 api call
          command: |
              curl --request GET --url https://circleci.com/api/v2/project/gh/vjpandian/cci-server4-api-tests/job/4 --header "Circle-Token: $CIRCLE_TOKEN"
              
  get-job-v1:
    executor: default
    steps:
      - run: 
          name: getJob v1
          command: |
             curl https://<< pipeline.parameters.cci-hostname >>/api/v1.1/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM -H "Circle-Token: $CIRCLE_TOKEN"
  get-job-v2:
    executor: default
    steps:
      - run: 
          name: getJob v2 api call
          command: |
              curl --request GET --url https://<< pipeline.parameters.cci-hostname >>/api/v2/project/gh/vjpandian/cci-server4-api-tests/job/$CIRCLE_PREVIOUS_BUILD_NUM --header "Circle-Token: $CIRCLE_TOKEN"
workflows:
  main:
    jobs:
      - get-job-v1
      - get-job-v2
      - get-job-v1-cloud:
             context: org-global
      - get-job-v2-cloud:
             context: org-global
    
