
version: 2.1
parameters:
  cci-hostname:
    type: string
    default: "server4.fieldeng-sphereci.com"
executors:
  default:
    docker:
      - image: cimg/base:stable
jobs:
  get-job-v1-cloud:
    executor: default
    steps:
      - run: 
          name: getJob v1
          command: |
             curl https://circleci.com/api/v1.1/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/4 -H "Circle-Token: $CIRCLE_TOKEN"

  
  get-job-v2-cloud:
    executor: default
    steps:
      - run: 
          name: getJob v2 api call
          command: |
              curl --request GET --url https://circleci.com/api/v2/project/gh/vjpandian/cci-server4-api-tests/job/4 --header "Circle-Token: $CIRCLE_TOKEN"
              
  get-user-admin-v1:
    executor: default
    steps:
      - run: 
          name: Set User to suspended to false
          command: |
             curl -s -H "Circle-Token: $CIRCLE_TOKEN" https://<<pipeline.parameters.cci-hostname>>/api/v1/admin/users | jq '.[] | select(.login=="samba")'

      - run: 
          name: getJob v1 for successful build num 19
          command: |
             curl https://<< pipeline.parameters.cci-hostname >>/api/v1.1/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/19 -H "Circle-Token: $CIRCLE_TOKEN"
  get-job-v2:
    executor: default
    steps:
      - run: 
          name: getJob v2 api call
          command: |
              curl --request GET --url https://<< pipeline.parameters.cci-hostname >>/api/v2/project/gh/vjpandian/cci-server4-api-tests/job/$CIRCLE_PREVIOUS_BUILD_NUM --header "Circle-Token: $CIRCLE_TOKEN"
workflows:
  main:
    jobs:
      - get-user-admin-v1:
           context: server4-fieldeng-token
    
