
version: 2.1
parameters:
  cci-hostname:
    type: string
    default: "cci-server-test.eks-dev.sphereci.com"
executors:
  default:
    docker:
      - image: cimg/base:stable
jobs:
  get-jobs-v2:
    executor: default
    steps:
      - run: echo "hello"
      - run: 
          name: 
          command: |
              JOB_NUMBER=$(($CIRCLE_BUILD_NUM - 1))
              echo "Previous job number is $JOB_NUMBER"
              curl --request GET \
                 --url 'https://<< pipeline.parameters.cci-hostname >>/api/v2/project/gh/vjpandian/cci-server4-api-tests/job/$CIRCLE_PREVIOUS_BUILD_NUM' \
                 --header 'Circle-Token: $CIRCLE_TOKEN'
workflows:
  main:
    jobs:
      - get-jobs-v2
    
